### PR TITLE
Feature: Allow using with self-hosted plausible instance

### PR DESCRIPTION
**Pull request by aareman**
See commit message for more details. First time contributing to this project, I read the Contrib doc, but not sure the best way to test this, and didn't see any tests for settings etc...

Please let me know if there are any changes you would like me to make.

### CODE REVIEW

**Comment by imankulov** [comment]
Thanks for your contribution, @aareman! I'll review it later today

**Comment by aareman** [comment]
Great, thanks @imankulov, looking forward. Just a heads up, I'll be offline till Tuesday.

**Comment by imankulov** [comment]
Looking good. I merged the PR and will make a new release a bit later. Thanks a lot for your contribution 🚀

**Comment by imankulov** [comment]
A new release is on PyPI 🎉

**Pull request merged**
